"""relationships fixed

Revision ID: 6effb1248196
Revises: e1b9d9432c0f
Create Date: 2018-09-17 12:26:36.700843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6effb1248196'
down_revision = 'e1b9d9432c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'data', type_='foreignkey')
    op.drop_column('data', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'data', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
